In [1]:
import pandas as pd
import numpy as np

In [ ]:
# USER MOVIE RECOMMENDATION SYSTEM
#1.import libraries and dataset
#2.identify total n of users and movies
#3.split data into training and testing sets
#4.populate train test metrics with random ratings
#5.create cosine similarity metrics for users n movies
#perform predictions

In [10]:
df=pd.read_csv("C:\\Users\\91630\\OneDrive\\Desktop\\jupyter\\Recommend.csv")
df

user_id  movie_id  rating  timestamp
0          186       302       3  891717742
1           22       377       1  878887116
2          244        51       2  880606923
3          166       346       1  886397596
4          298       474       4  884182806
...        ...       ...     ...        ...
99994      880       476       3  880175444
99995      716       204       5  879795543
99996      276      1090       1  874795795
99997       13       225       2  882399156
99998       12       203       3  879959583

[99999 rows x 4 columns]

In [ ]:
#calculate no of users and movies since we are developing user recommendation model

In [12]:
from sklearn.model_selection import train_test_split
n_users=df.user_id.unique().shape[0]
n_movies=df.movie_id.unique().shape[0]

In [13]:
#split data into training and testing

In [14]:
train_data,test_data=train_test_split(df,test_size=0.25)

In [20]:
#create zero matrix
train_data_matrix=np.zeros((n_users,n_movies))
#populate train and test matrix
for i in train_data.itertuples():
    train_data_matrix[i[1]-1,i[2]-1]=i[3]
train_data_matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [21]:
#create zero matrix
test_data_matrix=np.zeros((n_users,n_movies))
#populate train and test matrix
for i in test_data.itertuples():
    test_data_matrix[i[1]-1,i[2]-1]=i[3]
test_data_matrix

array([[0., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
#create cosine similarity measures

In [25]:
from sklearn.metrics import pairwise_distances
user_simi=pairwise_distances(train_data_matrix,metric="cosine")
movie_simi=pairwise_distances(train_data_matrix.T,metric="cosine")
mean_user_rating=train_data_matrix.mean(axis=1)[:,np.newaxis]
ratings_diff=train_data_matrix- mean_user_rating
user_pred= mean_user_rating+ user_simi.dot(ratings_diff)/np.array([np.abs(user_simi).sum(axis=1)]).T
user_pred

array([[ 1.62292648,  0.57814032,  0.50475736, ...,  0.31535571,
         0.31533833,  0.31287441],
       [ 1.36375709,  0.26270742,  0.14324895, ..., -0.06097007,
        -0.05972979, -0.06296172],
       [ 1.36138101,  0.22157515,  0.11166252, ..., -0.10019551,
        -0.09833117, -0.10157262],
       ...,
       [ 1.23912599,  0.1909717 ,  0.07906291, ..., -0.1206851 ,
        -0.11975903, -0.12289945],
       [ 1.39838102,  0.29243414,  0.20719019, ..., -0.00253859,
        -0.00190004, -0.00456945],
       [ 1.43393692,  0.35597716,  0.28968655, ...,  0.10429599,
         0.10433733,  0.10180754]])